name: Homework workflow

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture: ['x86', 'x64']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - uses: action/checkout@v3
      - name: Set up Python 3.x
        uses: action/setup-python@v4
        with:
          python-version: '3.x'
          architecture: ${{ matrix.architecture }}

      - name: Install Requirements
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: flake8
        run: |
            pip install flake8
            flake8 .
        continue-on-error: true

      - name: pytest
        run: |
            pip install pytest
            pytest .
