name: Homework workflow

on: [push]

jobs:
  'lint&test':

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
            python -m pip install --upgrade pip
            pip install flake8
            pip install -r requirements.txt

      - name: flake8
        run: |
            flake8 .
        continue-on-error: true

      - name: pytest
        run: |
            pytest .
